[agent]
  interval = "5s"
  flush_interval = "5s"

[[inputs.mqtt_consumer]]
  servers = ["tcp://172.17.0.3:1883"]
  topics  = ["maquette/pzem"]
  data_format = "json"
  json_time_key = ""
  json_string_fields = []

[[outputs.influxdb_v2]]
  urls   = ["http://172.17.0.4:8086"]
  token  = "6SKMTDLefGzAv7TbVuennkmY33BiiOLibqneH6wBAzoGguCUjShsebZWk6v4Jb-Hf25lZsK22IHnlM0Hxg8Adg=="
  organization = "pfe_agricole"
  bucket = "maquette"
